const sequelize = require("../sequelize");

const AssignedBadge = sequelize.define(
  "assigned_badge",
  {
    // relevant columns and foreign keys are generated by Sequelize when
    // specifying the 'many to many' relationship:
    // User.belongsToMany(Badge, { through: AssignedBadge });
    // Badge.belongsToMany(User, { through: AssignedBadge });
  },
  {
    timestamps: false,
  }
);

module.exports = AssignedBadge;
